project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2022, Testy R. Testman" 
    right: 
      - icon: github
        href: https://github.com/Seanlee01
      - icon: twitter 
        href: https://twitter.com/Seanlee2001
  title: "Sean's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://www.google.com/
        text: Resume
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



