---
title: "News Writing Piece"
---

### **INCLUDING ASIAN AMERICAN NARRATIVES: A KOREAN AMERICAN PASTOR'S PERSPECTIVE ON ENERGY CONSERVATION**

Sean Lee

August 5, 2021

Energy conservation is the preservation of energy resources, such as light, fuel, etc. Despite the various contributions Asian Americans can bring to the table, they have often been left out of the conversation on energy conservation. For example, Asian American environmentalists were [ostracized from the environmental movement](https://www.nrdc.org/stories/why-environmental-movement-should-stop-ignoring-asian-americans) and received little support due to the model minority myth. The myth creates a misconception that all Asian Americans lived a successful life with outstanding job positions. However, this is not always true because some Asian Americans do live in poverty and get little support from the government including in environmental justice work.   

Today, energy conservation has become a large social movement as various initiatives have been created around the world. For example, The [SuperHomes](https://superhomes.org.uk/) project is a network under the National Energy Foundation. This project has refurbished over 200 households to use solar energy in order to reduce carbon emissions. However, as research and data accumulate for energy conservation initiatives, Asian Americans are often overlooked despite their deep concern for energy conservation and the environment.[EcoAmerica](https://ecoamerica.org/wp-content/uploads/2014/09/eA_American_Climate_Values_2014_Insights_by_Racial_Ethnic_Groups.pdf) revealed that 36% of concerned Asian Americans are unsure about what actions to take against climate change due to a lack of information and inclusion. This is a deep contrast to only 24% of concerned Americans among all ethnic groups. 

Many Asian cultures have a more collectivist mindset and deeply care for one another in their community. For them, the "[we transcend the I](https://www.nrdc.org/stories/why-environmental-movement-should-stop-ignoring-asian-americans)" and energy conservation is a way for them to ensure that future generations are able to enjoy the same resources as them. It is time that the Asian American community is included in this crucial energy conservation movement. 

One example is Ted Kang, a Korean American who exemplifies the ways an individual can conserve energy. He is a Christian pastor in Glendale, California, and a school board member for New Covenant Academy. Ted Kang, who identifies as the "turn off the lights" guy in his family, emphasizes, "There's a stake in it for us too because we want to keep \[the environment\] for the future".

### **"THERE'S A STAKE IN IT FOR US TOO BECAUSE WE WANT TO KEEP \[THE ENVIRONMENT\] FOR THE FUTURE". - PASTOR TED KANG**

Over his 45 years of residency in the U.S., Pastor Kang has taken notice of some of the environmental issues California faces. He recounted the numerous smog days in Los Angeles during the 1970s when the poor air quality forced residents to stay inside their homes. These instances made Pastor Kang recognize the environmental damage left behind by human civilization. 

On an individual level, Pastor Kang conserves energy in various ways. He routinely preserves energy by turning off unused lights, reducing air conditioning usage, and minimizing driving his car to cut down on gasoline use. On a community level, his church utilizes biodegradable plates and utensils during fellowship. This helps reduce the energy used in the processing and manufacturing of these products. 

However, despite these successes, Pastor Kang acknowledges the cultural obstacles, such as language barriers, that recent Asian immigrants face in understanding the various approaches to energy conservation. He also notes that there is a disparity between recent Asian American immigrants versus those who have been in the U.S for generations. Pastor Kang explains that practicing energy conservation is a luxury to those who have recently immigrated to America as they are unaccustomed to Western society and are struggling to stabilize their new lives. Their immediate struggle is to build their new life in America through financial stability, which leaves little room for thought about energy efficiency. This means that recent immigrants can know how to practice energy conservation; however, they may not have many chances to practice it.  

Moreover, [recent immigrants are often limited in English](https://www.pewresearch.org/fact-tank/2020/07/01/polling-methods-are-changing-but-reporting-the-views-of-asian-americans-remains-a-challenge/) with little to no resources about energy conservation translated to their native language. Pastor Kang personally noticed that, despite a larger population of first-generation Korean Americans in the area, most information is mainly translated into Chinese or Japanese. Thus, the outreach to the entire Asian American community is still smaller than needed.

The [PEW Research Center](https://www.pewresearch.org/fact-tank/2021/04/29/key-facts-about-asian-americans/) estimates that Asian Americans will be the nation's largest immigrant group by 2050. With an increase in the Asian American immigrant population in the next few decades, Pastor Kang's concern of the lack of information translation for the greater Asian American community proves to be a legitimate worry. In order for Asian Americans to expand and further their conservation practices, it is vital that they are provided with the resources necessary to recognize and understand how energy conservation is tied to community values.

[While there is little to no data](https://www.nrdc.org/experts/vijay-limaye/when-asian-americans-are-missing-public-health-data-its-harder-protect-them) about how the Asian American community is involved in energy conservation, they should not be excluded in future energy conservation advancements and conservation efforts. There are people within the Asian American community who have been conserving energy. For example, people like Pastor Kang have already made simple energy conservation lifestyle changes. Furthermore, the current and future generations can discover new ways to conserve energy through a more creative lens. This can be from giving more resources to our community or even advising the youth to practice conservation based on given guidelines from the state or non-profits.   

From Pastor Kang, we are able to see there are people out there in the Asian American community who take action with energy conservation by sharing their historical ancestral background and the lack of representation they've noticed for years. We need to continue the work to help our community understand energy conservation and begin to practice it. Start the conversation in your own homes about energy conservation and find out what your community needs.

\
