---
title: "Professional Work"
---

### *This is a paper I have done last semester in one of my SMPA class. The topic was on the disinformation we encounter in our current society and how it has been an increasing issue not just within the US but worldwide in our digital era. Used some of my past readings/sources to back up my claim.*

                Disinformation in our media and towards the public

Disinformation within our media has always been here and it won't stop. It is up to journalists and students like us to get the right education by rejecting this morality. To start off, a definition of disinformation according to Merriam-Webster is false information that is intentionally trying to influence the public by rejecting the truth. Some disinformation is easy to find and some are tricky based on the scenario. For example, when people talk about the Covid vaccines and how they are against them, the conversation does not end there. These kinds of discussions, later on, go in deeper with politics, the origin of Covid, vaccine conspiracies, and personal rights. In addition, when news organizations bandwagon with this hypothesis it creates more chaos for disinformation because they are helping the concept itself out to the public. I believe the solution to disinformation is simple. It's about educating ourselves and making our own judgments on specific studies. Our society should not worry about changing other people's abilities to share disinformation but evaluate how to approach the deceptive features our media can present. Essentially, being able to choose the right and wrongs along with not being gullible with non-credible sources. Disinformation in news has been detrimental to journalism and is it our job to know what media organizations are doing to prevent it and journalists/researchers explanation of what is at stake. 

Ernst and Young (EY) a multinational professional media service conducted research on how fake news is a threat to media organizations and how they needed to tackle these cases. Their project is divided into two chapters. The first chapter gives an overview of the amount of growth in fake news and how it is widespread throughout most media platforms. Chapter 2 talks about how to fight fake news and gives a layout of strategies in order to combat disinformation. Emmanuel Vignal critically talks about how fake news will continue to spread like wildfire if there isn't a conventional journalistic inquiry and fact-checking. The reality is that if we had no fact-checkers and credible people being involved, the constant pattern of disinformation will continue to flow on by making the audience confused with falsehood. Fake news is not just in the newsroom, it's everywhere from broadcast, print, digital, online forum sites, and social media apps. The spread of fake news does not just become a political problem as we might just assume. It creates a problem where we have an issue with advertising and the audience. Vignal states "if audiences no longer trust media brands as reliable sources of accurate information, brand revenue and sustainability can suffer" which means no money and views. In order to regulate disinformation, some media companies and platforms inside the European Union acknowledged having the EU Code of Practice on Disinformation was a good idea. It was pretty much a paradigm self-regulatory that deprived fake ideas of being presented in ads, institutions, political campaigns, and more. Now, of course, this code of conduct did not prevent every disinformation out there. The key path according to Vignal is to establish the most effective method: truth. The first method he discusses is about creating a high degree of transparency, accountability, and ethics in order to have a well-rounded critique of journalism. Second, increase cybersecurity to avoid vulnerabilities that can result in fake news. Third, monitor information on news sites, social media, and other interactive channels for potentially detrimental fake news. Lastly, develop a crisis communications plan so that your organization can act thoroughly when a crisis occurs unexpectedly. 

Building on the argument of disinformation, Shane Greenup from Misinfocon tells us how he is working on a project that is tackling disinformation. He describes how journalists can use simulators to fact-check their work or others' work posted online. These simulators have been automated by real people, artificial intelligence, and metadata. If we look like NewsGuard, Factmata, and Our.News they are all fact-checkers. NewsGuard is a fact-checking tool used by real trained researchers and will find out what is permitted in journalism. Factmata is the AI that is doing the work by searching everything related to whatever topic in journalism. A lot of people relate Factmata to the plagiarism detector Turnitin. Our.News was a website that evaluated news stories and offered more details on the publisher of each source along with any additional facts you had to know about the primary source. Therefore, Greenup's project offers how technological advancement in our society can help disinformation in journalism because clearly, a human being cannot catch every single aspect of how disinformation. All of these tools come in handy when we encounter fake news in a more complex way. 

Brandy Zadrozny from NBC news informs us on what researchers have seen with disinformation regarding the Covid pandemic. The three main researchers Donovan, Wardle, and Starbird all agreed how the pandemic has also turned into an infodemic. Social media platforms help people who spread misinformation on Covid because of how easy it is to deceive people. What stood out to me was when Donovan was mentioning how "information was cheap to produce and having knowledge is expensive." I agree with her quote because making fake things about Covid can be easy since you can find a non-credible source online easily. However, having the knowledge is not something that everyone has; especially with Covid since it requires authentic research and investigation. Similarly, Zadrozny's reading gives a good helpful connection to Bailey's reading when it comes to how disinformation is part of polarization. Bailey's reading says how no matter what the discretion might be there will always be people who use disinformation just because they don't appreciate the other side or a given topic like Covid. The example he gave was a Trump supporter at a political rally holding up a t-shirt that indicates "fake news." Something like this isn't going to stop free speech or media distrust. That's why Bailey tells journalists to forget about satisfying everyone and continue to do their part by giving out facts to improve the journalistic society. In contrast, Miller & Asbury's and Chideya's reading gives us an insight into personal rights and cultural competency. Miller & Asbury's content behind readings talks about how protesters do not like their faces to be shown on camera and photographers saying their rights in public. Both sides of the aisle have an argumentative point but what journalists are emphasizing is the world public. In public, whether that is a protest or not, they have the right to take picture of a group protest for journalism. However, it is still an ongoing dilemma so journalists are still vigilant about close-up shots and ask for permission when it comes to individual shots. I believe disinformation can have a connection here when it comes to photojournalism and how the image is the wrong portrayal. Finally, Chideya's concept of cultural competence and war along with how this has a correlation with disinformation. She heavily connects culture war with disinformation because of how fast has been erupting and fact-checking is not always the solution to culture war. An example of a culture war disinformation case she expressed is how people from Ohio are more worried about the Southern border compared to the people actually living there. This brings it back to the cultural disinformation people can have and journalists do not seem to notice it quickly enough. 

In conclusion, the entirety of disinformation in journalism has been frustrating and inevitable. There isn't a sophisticated way of preventing disinformation completely because of how overwhelmingly spreads on all media platforms. The challenge for us and journalists is how do we make disinformation happen a little less in the future than it is now. The best way to feel optimistic about disinformation is the number of people we have in academics that can educate society and come up with lessons that can override disinformation. Additionally, technology to some extent we have to thank since these AI tools help us easily navigate what is good and bad in print journalism. As long as we diligently continue this path by educating others then it would be a pattern we see and others who did not know about a certain topic in journalism can be influenced. As a result, a new policy I would want my news organization to have is by coming up with a specific focus in the area of study. For example, have a credible journalist in a certain field that practice the work on a daily basis. Then, this would lead to clarity and have a person to look up to when you encounter disinformation on that topic.  \
