---
title: "Analysis Walkthrough"
author: "Sean Lee"
format:
  html:
    self-contained: true
    code-fold: true
    code-tools: true

---

We'll start by loading the libraries and install tidyverse.

```{r}
#first we'll load our libraries
#make sure to install the tidyverse if it's not already installed
library(tidyverse)
library(lubridate)
```

We're going to look at some sample data from Texas on housing prices throughout the state. 

First, we will load the data.
```{r}
# run this line below load the data for this assignment
impeach <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRh8d5JaDqBtByzNw2JZF3idaACobDhhk-p7chJoktA0HawELHFOvjQOqCpzGA4MGONvPlR7GASqW-K/pub?gid=1765341510&single=true&output=csv")
```
We are going to see file called "impeach" and see which members supporte impeachment or not.

```{r}
# it will load a dataframe called "impeach," containing U.S. House Democrats
# and whether they supported impeachment along with when they announced such support
```

Now use the R codes we have learned throughout class. 

```{r}
# FOR EACH OF THE QUESTIONS BELOW, WRITE YOUR WORKING R CODE TO RETURN THE REQUESTED RESULTS
# USE COMMENTS (PREFACED BY THE #) TO ACCOMPANY YOUR CODE TO EXPLAIN WHAT YOU'RE DOING 
# FOR EACH STEP
```


```{r}
# 1) The column "for_impeachment" indicates whether the member has publicly called for
# an impeachment inquiry. Filter to return only the ones where the answer is NO.    

impeach %>% 
  filter(for_impeachment == "NO")
```

```{r}
# 2) Filter to return only results where a member is both against impeachment, and comes from a 
# district that President Trump won in 2016 (which is noted in the "p16winningparty" column)

impeach %>% 
  filter(for_impeachment == "NO") %>% 
  filter(p16winningparty == "R")
```

```{r}
# 3) Filter for only results where a member is against impeachment, comes from a 
# district that President Trump won in 2016 (which is noted in the "p16winningparty" column),
# and also comes from a district that Mitt Romney won in 2012 ("p12winningparty").

impeach %>% 
  filter(for_impeachment == "NO") %>% 
  filter(p16winningparty == "R") %>% 
  filter(p12winningparty == "R")
```

```{r}
# 4) Filter for only results from September 2019 where a member is a YES for impeachment. 

impeach %>% 
  filter(for_impeachment == "YES") %>% 
  filter(date_year == "2019") %>% 
  filter(date_month == "9")
```

```{r}
# 5) Filter for only results where a member is a YES for impeachment and is from a district
# where Clinton won more than 70 percent of the vote in 2016 (found in column "clinton_percent")

impeach %>% 
  filter(for_impeachment == "YES") %>% 
  filter(clinton_percent > 70)
```

```{r}
# 6) Sort the entire dataframe based on the percentage of a district that has a 
# bachelor's degree or higher ("pct_bachelors"), from lowest to highest

impeach %>% 
  arrange(pct_bachelors)
```

```{r}
# 7) Sort the just those who are NO on impeachment based on the percentage of a district that has a 
# bachelor's degree or higher ("pct_bachelors"), from lowest to highest

impeach %>% 
  filter(for_impeachment == "NO") %>% 
  arrange(pct_bachelors)
```

```{r}
# 8) Sort the just those who are NO on impeachment based on the percentage of a district that has a 
# bachelor's degree or higher ("pct_bachelors"), from lowest to highest.
# Then filter those records by only those whose bachelor's percentage is below the national average (found
# in the "pct_bachelors_compared_to_national" column).

impeach %>% 
  filter(for_impeachment == "NO") %>% 
  arrange(pct_bachelors) %>% 
  filter(pct_bachelors_compared_to_national == "BELOW")
```

```{r}
# 9) Filter for only members from New Jersey who are NO on impeachment

impeach %>% 
  filter(state == "NJ", for_impeachment == "NO")
```

```{r}
# 10) Filter for those who were YES on impeachment, with a declared date prior to 2019. So only
# those with dates before 2019.  Then sort those so that the highest Clinton vote percentages are 
# at the top.   

impeach %>% 
  filter(for_impeachment == "YES") %>% 
  filter(date_year < 2019) %>% 
  arrange(clinton_percent)
```

```{r}
# 11) Answer this question with a single numeric answer, and show the R code you
# used to reach that answer: How many members in the dataset who are holdouts on impeachment
# come from districts with a GDP below the national figure?
# Hint: there's a function called nrow() that tells you how many rows are in a dataframe

impeach %>% 
  filter(for_impeachment == "YES") %>% 
  filter(gdp_above_national == "BELOW") %>% 
  nrow()
```
